services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cube
      MYSQL_USER: cube
      MYSQL_PASSWORD: cube
    volumes:
      - ./docker/db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8081:80"