name: compile-app-and-list-files
run-name: ${{ github.actor }} est en train de compiler l'application et d'afficher la liste des fichiers
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - users: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd test-ci/ && git pull && npm install && npm run build && pm2 stop npm && pm2 start npm"